@ECHO OFF
COLOR 0c
TITLE IHORB AND ROMAH FIX FOR RESOLUTION FOR PARSEC IN AZURE VM
ECHO FIXING RESOLUTION. PUFF
C:\nvcli.exe -x 1920 -y 1080
ECHO RESOLUTION FOR CURRENT DISPLAY WAS FIXED !
PAUSE > nul
EXIT
